name: Build

on:
  repository_dispatch:
    types: [ build ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "linux/amd64"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Build and push
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/receipt-wrangler:latest
          build-args: |
            VERSION=${{ github.event.client_payload.version }}
            BUILD_DATE=${{ github.event.client_payload.build-date }}
